openapi: 3.0.0
info:
  title: Pet store
  version: v2
tags: []
paths:
  /pets:
    get:
      operationId: Pets_getPets
      description: Get all pets
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/MyApiCommon.PageCursor'
        - name: size
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/MyApiCommon.PageSize'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
                  links:
                    $ref: '#/components/schemas/MyApiCommon.PageLinks'
                  meta:
                    $ref: '#/components/schemas/MyApiCommon.PageMeta'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyApiCommon.ErrorObject'
  /pets/{id}:
    get:
      operationId: Pets_getPetById
      description: Get a pet by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyApiCommon.ErrorObject'
components:
  schemas:
    BasePet:
      type: object
      required:
        - id
        - category
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        links:
          $ref: '#/components/schemas/MyApiCommon.ObjectLink'
    Cat:
      type: object
      required:
        - id
        - category
        - kind
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        links:
          $ref: '#/components/schemas/MyApiCommon.ObjectLink'
        kind:
          type: string
          enum:
            - cat
        color:
          type: string
        address:
          type: string
          default: street
    Category:
      type: string
      enum:
        - domestic
        - wild
    Dog:
      type: object
      required:
        - id
        - category
        - kind
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        links:
          $ref: '#/components/schemas/MyApiCommon.ObjectLink'
        kind:
          type: string
          enum:
            - dog
        breed:
          type: string
        address:
          type: string
          default: wild
    MyApiCommon.ErrorObject:
      type: object
      required:
        - status
      properties:
        status:
          type: string
        id:
          type: string
        code:
          type: string
        title:
          type: string
      description: Error object
    MyApiCommon.ObjectLink:
      type: object
      properties:
        self:
          type: string
        related:
          type: object
          properties:
            href:
              type: string
            title:
              type: string
    MyApiCommon.PageCursor:
      type: string
      description: Cursor for pagination
    MyApiCommon.PageLinks:
      type: object
      properties:
        self:
          type: string
        first:
          type: string
        prev:
          type: string
        next:
          type: string
        last:
          type: string
    MyApiCommon.PageMeta:
      type: object
      additionalProperties: {}
      description: Metadata for pagination
    MyApiCommon.PageSize:
      type: integer
      description: Size for pagination
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      discriminator:
        propertyName: kind
        mapping:
          dog: '#/components/schemas/Dog'
          cat: '#/components/schemas/Cat'
    Versions:
      type: string
      enum:
        - v1
        - v2
servers:
  - url: https://api.example.com
    description: Example endpoint
    variables: {}
