openapi: 3.0.0
info:
  title: Pet store
  version: v1
tags: []
paths:
  /pets:
    get:
      operationId: Pets_getPets
      description: Get all pets
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyApiCommon.ErrorObject'
  /pets/{id}:
    get:
      operationId: Pets_getPetById
      description: Get a pet by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyApiCommon.ErrorObject'
components:
  schemas:
    BasePet:
      type: object
      required:
        - id
        - category
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
    Cat:
      type: object
      required:
        - id
        - category
        - kind
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        kind:
          type: string
          enum:
            - cat
        color:
          type: string
        address:
          type: string
          default: street
    Category:
      type: string
      enum:
        - domestic
        - wild
    Dog:
      type: object
      required:
        - id
        - category
        - kind
      properties:
        id:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        kind:
          type: string
          enum:
            - dog
        breed:
          type: string
        address:
          type: string
          default: wild
    MyApiCommon.ErrorObject:
      type: object
      required:
        - status
      properties:
        status:
          type: string
        id:
          type: string
        code:
          type: string
        title:
          type: string
      description: Error object
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      discriminator:
        propertyName: kind
        mapping:
          dog: '#/components/schemas/Dog'
          cat: '#/components/schemas/Cat'
    Versions:
      type: string
      enum:
        - v1
servers:
  - url: https://api.example.com
    description: Example endpoint
    variables: {}
